<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ValidationInvoicesAPBiz" targetNamespace="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz" xmlns:tns="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns0="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
<wsdl:types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz/types" elementFormDefault="qualified">
<xsd:import namespace="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz" schemaLocation="ValidationInvoicesAPBiz.xsd"/>
</xsd:schema>
</wsdl:types>
<wsdl:message name="ValidateInvoicesAPRq">
<wsdl:part name="ValidateInvoicesAPRqPart" element="tns:ValidateInvoicesAPRq"/>
</wsdl:message>
<wsdl:portType name="ValidationInvoicesAPBizPortType">
<wsdl:operation name="ValidateInvoicesAP">
<wsdl:input message="tns:ValidateInvoicesAPRq"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="ValidationInvoicesAPBizBinding" type="tns:ValidationInvoicesAPBizPortType">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="ValidateInvoicesAP">
<soap:operation soapAction="http://soa.estrellaroja.com.mx/ValidationInvoicesAPBiz/ValidateInvoicesAP"/>
<wsdl:input>
<soap:body use="literal" parts="ValidateInvoicesAPRqPart"/>
</wsdl:input>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="ValidationInvoicesAPBiz">
<wsdl:port name="ValidationInvoicesAPBizPortType" binding="tns:ValidationInvoicesAPBizBinding">
<soap:address location="http://ersoaprod02lab-soa-0.snproduccin.vcner.oraclevcn.com:9073/soa-infra/services/DEV/ValidationInvoicesAPBiz/ValidationInvoicesAPBiz"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>
