<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="mediatorConciliationEnt" targetNamespace="http://soa.estrellaroja.com.mx/ConciliationEnt" xmlns:tns="http://soa.estrellaroja.com.mx/ConciliationEnt" xmlns:inp1="http://soa.estrellaroja.com.mx/ConciliationEnt" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
<plnk:partnerLinkType name="Conciliation">
<plnk:role name="ConciliationProvider" portType="client:Conciliation"/>
</plnk:partnerLinkType>
<wsdl:types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://soa.estrellaroja.com.mx/ConciliationEnt" xmlns:inp1="http://soa.estrellaroja.com.mx/ConciliationEnt" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
<xsd:import namespace="http://soa.estrellaroja.com.mx/ConciliationEnt" schemaLocation="ConciliationEnt.xsd"/>
</xsd:schema>
</wsdl:types>
<wsdl:message name="ConciliationRqM">
<wsdl:part name="ConciliationRqP" element="tns:ConciliationEntRq"/>
</wsdl:message>
<wsdl:message name="ConciliationRsM">
<wsdl:part name="ConciliationRsP" element="tns:ConciliationEntRs"/>
</wsdl:message>
<wsdl:portType name="ConciliationEntPortType">
<wsdl:operation name="Conciliation">
<wsdl:input message="tns:ConciliationRqM"/>
<wsdl:output message="tns:ConciliationRsM"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="ConciliationEntPortTypeSOAP11Binding" type="tns:ConciliationEntPortType">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="Conciliation">
<soap:operation style="document" soapAction="http://soa.estrellaroja.com.mx/ConciliationEnt/Conciliation"/>
<wsdl:input>
<soap:body use="literal" parts="ConciliationRqP"/>
</wsdl:input>
<wsdl:output>
<soap:body use="literal" parts="ConciliationRsP"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="ConciliationEntService">
<wsdl:port name="ConciliationEntPort" binding="tns:ConciliationEntPortTypeSOAP11Binding">
<soap:address location="http://ersoaprd-soa-0.snproduccin.vcner.oraclevcn.com:9073/soa-infra/services/PROD/ConciliationEnt/ConciliationEnt"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>
