<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="PaymentComplementBiz" targetNamespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz" xmlns:tns="http://soa.estrellaroja.com.mx/PaymentComplementBiz" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns0="http://soa.estrellaroja.com.mx/PaymentComplementBiz" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
<wsdl:types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz/types" elementFormDefault="qualified">
<xsd:import namespace="http://soa.estrellaroja.com.mx/PaymentComplementBiz" schemaLocation="PaymentComplementBiz.xsd"/>
</xsd:schema>
</wsdl:types>
<wsdl:message name="StampPaymentComplementRq">
<wsdl:part name="StampPaymentComplementRq" element="ns0:StampPaymentComplementRq"/>
</wsdl:message>
<wsdl:message name="StampPaymentComplementRs">
<wsdl:part name="StampPaymentComplementRs" element="ns0:StampPaymentComplementRs"/>
</wsdl:message>
<wsdl:portType name="PaymentComplementBizPortType">
<wsdl:operation name="StampPaymentComplement">
<wsdl:input message="tns:StampPaymentComplementRq"/>
<wsdl:output message="tns:StampPaymentComplementRs"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="PaymentComplementBizBinding" type="tns:PaymentComplementBizPortType">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="StampPaymentComplement">
<soap:operation soapAction="http://soa.estrellaroja.com.mx/PaymentComplementBiz/StampPaymentComplement"/>
<wsdl:input>
<soap:body use="literal" parts="StampPaymentComplementRq"/>
</wsdl:input>
<wsdl:output>
<soap:body use="literal" parts="StampPaymentComplementRs"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="PaymentComplementBiz">
<wsdl:port name="PaymentComplementBizPort" binding="tns:PaymentComplementBizBinding">
<soap:address location="http://ersoaprod02lab-soa-0.snproduccin.vcner.oraclevcn.com:9073/soa-infra/services/DEV/PaymentComplementBiz/PaymentComplementBiz"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>
